(part "XC6206P302MR-G"
    (packageRef "SOT95P280X130-3N")
    (interface
        (port "1" (symbPinId 1) (portName "VSS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "865-XC6206P302MR-G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Torex-Semiconductor/XC6206P302MR-G?qs=AsjdqWjXhJ%2FCPGHa4B8pZA%3D%3D")
    (property "Manufacturer_Name" "Torex")
    (property "Manufacturer_Part_Number" "XC6206P302MR-G")
    (property "Description" "1UA LOW QUIESCENT 3 TERMINAL, LO")
    (property "Datasheet_Link" "https://www.torexsemi.com/file/xc6206/XC6206.pdf")
    (property "symbolName1" "XC6206P302MR-G")
)
