(part "CVCO55BE-0400-0800"
    (packageRef "CVCO55BE04000800")
    (interface
        (port "1" (symbPinId 1) (portName "GROUND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GROUND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GROUND_4") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GROUND_5") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GROUND_6") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GROUND_7") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GROUND_8") (portType INOUT))
        (port "10" (symbPinId 10) (portName "RF-OUTPUT") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GROUND_9") (portType INOUT))
        (port "12" (symbPinId 12) (portName "GROUND_10") (portType INOUT))
        (port "13" (symbPinId 13) (portName "GROUND_11") (portType INOUT))
        (port "14" (symbPinId 14) (portName "VCC") (portType INOUT))
        (port "15" (symbPinId 15) (portName "GROUND_12") (portType INOUT))
        (port "16" (symbPinId 16) (portName "GROUND_13") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "Crystek")
    (property "Manufacturer_Part_Number" "CVCO55BE-0400-0800")
    (property "Mouser_Part_Number" "549-CV55BE0400-0800")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Crystek-Corporation/CVCO55BE-0400-0800?qs=O9nmv0aA33UiGXPclCNPWQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "VCO Oscillators 400MHz-800MHz")
    (property "Datasheet_Link" "http://www.crystek.com/microwave/admin/webapps/welcome/files/vco/CVCO55BE-0400-0800.pdf")
    (property "symbolName1" "CVCO55BE-0400-0800")
)
