(part "BGB_741L7ESD_E6327"
    (packageRef "BGB741L7ESDE6327")
    (interface
        (port "1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "BIASOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF-IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RF-OUT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "ON/OFF_CONTROL") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CURRENT_ADJUST") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "726-BGB741L7ESDE63")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/BGB-741L7ESD-E6327?qs=nTClRYuuQBouXaJjSylDSQ%3D%3D")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "BGB 741L7ESD E6327")
    (property "Description" "Infineon BGB741L7ESD BGB 741L7ESD E6327, RF Amplifier Low Noise, 21.5 dB 5 GHz, 6-Pin TSLP-7-1")
    (property "Datasheet_Link" "https://www.infineon.com/dgdl/Infineon-BGB741L7ESD-DS-v03_00-EN.pdf?fileId=5546d46265f064ff016638972c994ed7&redirId=115243")
    (property "symbolName1" "BGB_741L7ESD_E6327")
)
