(part "ADP7118AUJZ-5_0-R7"
    (packageRef "SOT95P280X100-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SENSE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADP7118AUJZ5.0R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP7118AUJZ-5.0-R7?qs=hpwIUhX6lWzp%252BHPslBdPxA%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP7118AUJZ-5.0-R7")
    (property "Description" "20 V, 200 mA, Low Noise, CMOS LDO Linear Regulator")
    (property "Datasheet_Link" "https://www.analog.com/ADP7118/datasheet")
    (property "symbolName1" "ADP7118AUJZ-5_0-R7")
)
