(part "PGA-103+"
    (packageRef "GVA63")
    (interface
        (port "1" (symbPinId 1) (portName "RF-IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF-OUT_&_DC_IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "139-PGA-103")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/PGA-103%2b?qs=xZ%2FP%252Ba9zWqZWniifnGTm5A%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "PGA-103+")
    (property "Description" "RF Amplifier SMT Low Noise Amplifier, 50Ohm - 4000 MHz, 50")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/PGA-103+.pdf")
    (property "symbolName1" "PGA-103+")
)
