(part "SXLP-450+"
    (packageRef "SXLP450")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GROUND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GROUND_4") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GROUND_5") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GROUND_6") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OUTPUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "SXLP-450+")
    (property "Description" "465MHz (Cutoff) Frequency Low Pass RF Filter (Radio Frequency) Bandwidth 2.5dB 8-SMD, No Lead")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/SXLP-450+.pdf?srsltid=AfmBOopyfng1W_JE_YCYT7VOxU4Z8bevNLx0xfxbggheauuZmJBv02wv")
    (property "symbolName1" "SXLP-450+")
)
