(part "ECS-TXO-2520MV-120-AY-TR"
    (packageRef "ECSTXO2520MV120AYTR")
    (interface
        (port "1" (symbPinId 1) (portName "TRI-STATE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "520-TXO2520MV120AYTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ECS/ECS-TXO-2520MV-120-AY-TR?qs=bAKSY%2FctAC6B08N7%252By9row%3D%3D")
    (property "Manufacturer_Name" "ECS")
    (property "Manufacturer_Part_Number" "ECS-TXO-2520MV-120-AY-TR")
    (property "Description" "TCXO Oscillators MultiVolt OSC TCXO 12.000MHZ CMOS SMD ECS-TXO-2520MV 12MHz CMOS +1.7V +3.6V +/-2.5ppm -30 C 85 C - Surface Mount 0.098" L x 0.079" W (2.50mm x 2.00mm) 0.035" (0.90mm) 4-SMD, No Lead (DFN, LCC)")
    (property "Datasheet_Link" "https://ecsxtal.com/store/pdf/ECS-TXO-2520MV.pdf")
    (property "symbolName1" "ECS-TXO-2520MV-120-AY-TR")
)
